<?php

namespace BrewMo\Application\Service;

use BrewMo\Domain\Recipe\Recipe;

/**
 * Service responsible for generating and synchronizing Dolibarr BOMs (llx_bom)
 * from BrewMo Recipes (Single Source of Truth).
 */
class RecipeBOMGeneratorService
{
    private object $db;

    public function __construct(object $db)
    {
        $this->db = $db;
    }

    /**
     * Generates or updates a Dolibarr Core BOM (llx_bom & llx_bom_line)
     * based on a BrewMo Recipe domain entity.
     *
     * @param Recipe $recipe
     * @param int $finishedProductId Dolibarr Product ID for the finished beer
     * @return int Dolibarr BOM Row ID
     */
    public function syncRecipeToDolibarrBOM(Recipe $recipe, int $finishedProductId): int
    {
        $label = 'Auto-BOM: ' . $recipe->getTitle() . ' (Generated by BrewMo)';
        
        // 1. Check if BOM already exists for this recipe/product
        $existingBomId = 0;
        $sqlCheck = "SELECT rowid FROM " . MAIN_DB_PREFIX . "bom WHERE fk_product = " . (int)$finishedProductId . " AND entity = 1 LIMIT 1";
        $resql = $this->db->query($sqlCheck);
        if ($resql && $this->db->num_rows($resql) > 0) {
            $obj = $this->db->fetch_object($resql);
            $existingBomId = (int)$obj->rowid;
        }

        if ($existingBomId > 0) {
            // Update existing BOM header
            $sqlUpdate = "UPDATE " . MAIN_DB_PREFIX . "bom SET label = '" . $this->db->escape($label) . "', qty = " . (float)$recipe->getTargetBatchSizeLiters() . ", tms = NOW() WHERE rowid = " . $existingBomId;
            $this->db->query($sqlUpdate);
            $bomId = $existingBomId;

            // Clear old BOM lines to overwrite with fresh recipe ingredients
            $this->db->query("DELETE FROM " . MAIN_DB_PREFIX . "bom_line WHERE fk_bom = " . $bomId);
        } else {
            // Create new Dolibarr BOM
            $sqlInsert = "INSERT INTO " . MAIN_DB_PREFIX . "bom (entity, ref, label, fk_product, qty, status, datec) VALUES (";
            $sqlInsert .= "1, ";
            $sqlInsert .= "'BOM-" . $this->db->escape($recipe->getRef()) . "', ";
            $sqlInsert .= "'" . $this->db->escape($label) . "', ";
            $sqlInsert .= (int)$finishedProductId . ", ";
            $sqlInsert .= (float)$recipe->getTargetBatchSizeLiters() . ", ";
            $sqlInsert .= "1, "; // Status = Validated
            $sqlInsert .= "NOW()";
            $sqlInsert .= ")";

            $this->db->query($sqlInsert);
            $bomId = (int)$this->db->last_insert_id(MAIN_DB_PREFIX . "bom");
        }

        // 2. Populate BOM Lines from Recipe Ingredients
        foreach ($recipe->getIngredients() as $ingredient) {
            $productId = $ingredient->getDolibarrProductId();
            $qty       = $ingredient->getAmount();

            if ($productId > 0 && $qty > 0) {
                $sqlLine = "INSERT INTO " . MAIN_DB_PREFIX . "bom_line (fk_bom, fk_product, qty, datec) VALUES (";
                $sqlLine .= $bomId . ", ";
                $sqlLine .= (int)$productId . ", ";
                $sqlLine .= (float)$qty . ", ";
                $sqlLine .= "NOW()";
                $sqlLine .= ")";

                $this->db->query($sqlLine);
            }
        }

        return $bomId;
    }
}
