<?php
class BrewmoEquipment {
    public $db,$id,$ref,$label,$efficiency_pct,$boiloff_l_h,$trub_loss_l,$lauter_deadspace_l,$mash_tun_l,$kettle_l,$note,$enabled;
    function __construct($db){ $this->db=$db; }
    function fetch($id){ $res=$this->db->query("SELECT * FROM ".MAIN_DB_PREFIX."brew_equipment WHERE rowid=".(int)$id); if($res&&$o=$this->db->fetch_object($res)){ foreach($o as $k=>$v)$this->$k=$v; $this->id=$o->rowid; return 1;} return -1; }
    function create($user){ global $conf; $sql="INSERT INTO ".MAIN_DB_PREFIX."brew_equipment(entity,ref,label,efficiency_pct,boiloff_l_h,trub_loss_l,lauter_deadspace_l,mash_tun_l,kettle_l,note,enabled) VALUES(".(int)$conf->entity.",'".$this->db->escape($this->ref)."','".$this->db->escape($this->label)."',".($this->efficiency_pct!==null?(float)$this->efficiency_pct:"NULL").",".($this->boiloff_l_h!==null?(float)$this->boiloff_l_h:"NULL").",".($this->trub_loss_l!==null?(float)$this->trub_loss_l:"NULL").",".($this->lauter_deadspace_l!==null?(float)$this->lauter_deadspace_l:"NULL").",".($this->mash_tun_l!==null?(float)$this->mash_tun_l:"NULL").",".($this->kettle_l!==null?(float)$this->kettle_l:"NULL").",'".$this->db->escape($this->note)."',".(int)$this->enabled.")"; if($this->db->query($sql)){ $this->id=$this->db->last_insert_id(MAIN_DB_PREFIX.'brew_equipment'); return $this->id;} return -1; }
    function update($user){ $sql="UPDATE ".MAIN_DB_PREFIX."brew_equipment SET ref='".$this->db->escape($this->ref)."',label='".$this->db->escape($this->label)."',efficiency_pct=".($this->efficiency_pct!==null?(float)$this->efficiency_pct:"NULL").",boiloff_l_h=".($this->boiloff_l_h!==null?(float)$this->boiloff_l_h:"NULL").",trub_loss_l=".($this->trub_loss_l!==null?(float)$this->trub_loss_l:"NULL").",lauter_deadspace_l=".($this->lauter_deadspace_l!==null?(float)$this->lauter_deadspace_l:"NULL").",mash_tun_l=".($this->mash_tun_l!==null?(float)$this->mash_tun_l:"NULL").",kettle_l=".($this->kettle_l!==null?(float)$this->kettle_l:"NULL").",note='".$this->db->escape($this->note)."',enabled=".(int)$this->enabled." WHERE rowid=".(int)$this->id; return $this->db->query($sql)?1:-1; }
    function delete($user){ return $this->db->query("DELETE FROM ".MAIN_DB_PREFIX."brew_equipment WHERE rowid=".(int)$this->id)?1:-1; }
}
